cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'



urlpatterns = [
    
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('cart/', include('cart.urls', namespace='cart' )),
    path('orders/',include('orders.urls',namespace='orders')),
    path('', include('shop.urls', namespace='shop')),

    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .import views

app_name = 'orders'

urlpatterns = [
    
    path('create/',views.order_create,name='order_create'),
    
    
    
]

shop/urls.py
from django.urls import path

from .import views


app_name = 'shop'


urlpatterns = [
    
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
]
# page pending on 402

cart/models.py
from django.db import models

# Create your models here.
# page pending on 442

orders/models.py
from django.db import models
from shop.models import Product
# Create your models here.



class Order(models.Model):
    
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    
    
    
    
    def __str__(self):
        return 'Order {} '.format(self.id)
    
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'
        
        
        
        
        
        







class OrderItem(models.Model):
    
    order = models.ForeignKey(Order,related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return self.id
    
    
    def get_cost(self):
        return self.price * self.quantity

    class Meta:
        db_table = 'Orderitem'
        managed = True
        verbose_name = 'OrderItem'
        verbose_name_plural = 'OrderItems'

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


# shop category model 
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    
    slug = models.SlugField(max_length=200,unique=True)
    
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        
     
    
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])
    
    
    
     


# shop product model 

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='media/',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    
    
    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)
        verbose_name = 'product'
        verbose_name_plural = 'products'
        
        
        
    
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id , self.slug])

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]



class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    
    
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)
    

orders/forms.py
from django import forms
from .models import Order


class OrderCreationForm(forms.ModelForm):
    class Meta:
        model = Order
        
        fields = ['first_name','last_name','email','postal_code','city','address']
    
        verbose_name = 'ordercreationform'
        verbose_name_plural = 'ordercreationforms'

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            
            initial={'quantity':item['quantity'],
                     
                     'update':True
                     
                     }
        )
    return render(request,'cart/detail.html',{'cart':cart})













@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity = cd['quantity'],
                 update_quantity = cd['update'])
        
        
    return redirect('cart:cart_detail')
    
    
    
    


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')    

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreationForm
from cart.cart import Cart

# Create your views here.



def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreationForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            
            # clear the cart 
            cart.clear()
            return render(request,'order/created.html',{'order':order}) 
                
                
    
    else:
        
        form = OrderCreationForm()
        
    return render(request,'order/create.html',{'cart':cart,'form':form})               

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

# Create your views here.


# product list display function
def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
        
    
    return render(request,'shop/list.html',{'category':category,
                                            'categories':categories,
                                            'products':products})    
    
    
    


# product detail view function 

def product_detail(request,id,slug):
    prod  = get_object_or_404(Product, id=id, slug=slug, available=True) 
    
    
    cart_product_form = CartAddProductForm()
    
    
    return render(request,'shop/detail.html',{'product':prod,'cart_product_form':cart_product_form})

cart/templates/cart/detail.html
{% extends "base/layout.html" %}

{% load static %}

{% block title %} Your Shopping Cart  {% endblock title %}


{% block content %}


    <div class="container">
        <div class="row">
        <table>
            <thead>
                <tr class="">

                    <th class="col">Image</th>
                    <th class="col">product</th>
                    <th class="col">Qunatity</th>
                    <th class="col">Remove</th>
                    <th class="col">Unit Price </th>
                    <th class="col">Price </th>
                </tr>
            </thead>




            <tbody>


                {% for item in cart  %}

                {% with product=item.product %}
                <tr>
                    <td>
                        <a href=" {{prodcut.get_absolute_url}} ">
                            <img src=" {{product.image.url}} " width="150px" height="150px" alt="">
                        </a>
                    </td>

                    <td class="">
                        {{product.name}}

                    </td>

                    <td>

                        <form action=" {% url 'cart:cart_add' product.id %} " method="post">
                            {% csrf_token %}

                            {{item.update_quantity_form.quantity}}
                            {{item.update_quantity_form.update}}

                            <input type="submit" class="btn btn-success m-auto btn-sm">

                        </form>



                        
                    </td>



                    <td>
                        <a href=" {% url 'cart:cart_remove' product.id %} ">Remove</a>
                    </td>

                    <td>
                        {{item.price}}
                    </td>

                    <td>{{item.total_price}}</td>
                </tr>
                {% endwith %}
                  
                {% endfor %}



                <tr class="badge badge-secondary ">
                    <td>Total</td>
                    <td> {{cart.get_total_price}} </td>
                </tr>



                

            </tbody>








        </table>



       
        </div>
         <p class=" pt-3 ">
             <a href=" {% url 'shop:product_list' %} " class="btn btn-info">Continue Shopping</a>

             <a href=" {% url 'orders:order_create' %} " class="btn btn-primary">CheckOut</a>

         </p>
    </div>






  
{% endblock content %}

orders/templates/order/create.html
{% extends "base/layout.html" %}
{% load crispy_forms_tags %}
{% block title %} Checkout {% endblock title %}



{% block content %}



<div class="container">
    <h5>Checkout</h5>
    <div class="row">
        <div class="col">
         
               <h5>Your Order</h5>

               <ul>
                   {% for item in cart %}

                   <li>
                       <strong>{{item.quantity}} </strong>
                       {{item.product.name}}
                       <span class="badge badge-secondary"> ${{item.total_price}} </span>
                   </li>

                   {% endfor %}

               </ul>
               <p class="badge badge-warning"> Total ${{cart.get_total_price}} </p>
        </div>
        <div class="col">
 <form action="" method="post">
     {% csrf_token %}
     {{form|crispy}}

     <input type="submit" class="btn btn-info" value="Place Order" name="" id="">
 </form>

           
        </div>
    </div>





{% endblock content %}

orders/templates/order/created.html
{% extends "base/layout.html" %}
{% block title %}
Thank you
{% endblock title %}
{% block content %}
<h1>Thank you</h1>
<p>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
{% endblock content %}

shop/templates/base/layout.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <title>   {% block title %}  {% endblock title %} </title>

</head>

<body>
    
  <!-- navbar start here -->
  {% include "shop/navbar.html" %}
  <!-- navbar ends here  -->




    {% block content %}


      
    {% endblock content %}
























    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

shop/templates/shop/detail.html
{% extends "base/layout.html" %}
{% load static %}

{% block title %} {{product.name}} {% endblock title %}



{% block content %}

<div class="container pt-2">

    <div class="row">

        <div class="col-md-8">

            <img src=" {{product.image.url}} " width="550px" height="550px">

        </div>








        <div class="col-md-4">
            <h3> {{product.name}} </h3>

            <a href="{{ product.category.get_absolute_url }}" class="float-right badge badge-success ">
                {{product.category}} </a>
            </a>

            <p> {{product.description}} </p>
            <small class="badge badge-warning"> &#x20b9 {{product.price}} </small>

            <form action=" {% url 'cart:cart_add' product.id %} " method="post">
                {% csrf_token %}

                {{cart_product_form}}

                <input type="submit" class="btn btn-outline-danger" value="Add Cart" name="add_to_cart"
                                id="add_to_cart">


            </form>

        </div>
    </div>
</div>


{% endblock content %}

shop/templates/shop/list.html
{% extends "base/layout.html" %}
{% load static %}
{% block title %} {% if category %} {{category.name}} {% else %} Products {% endif %} {% endblock title %}

{% block content %}



        <div class="container pt-2">


            <div class="row">

           
  

                <!-- product listing sectio  -->
                <div class="col-md-9">
                                <h3 class="text text-danger">{% if category %} {{category.name}} {% else %} Products {% endif %}</h3>
<hr>

                    <div class="row">
                    {% for prod  in products %}
                        <div class="col-sm-3">

                          <figure class="figure">
                             <a href=" {{prod.get_absolute_url}} "><img src=" {{prod.image.url}} " class="figure-img  rounded" alt="..." width="150px" height="150px"></a>
                            
                             <a href=" {{prod.get_absolute_url}} "><figcaption class="figure-caption">{{prod.name}} </figcaption></a>
                          </figure>
                        <p class="badge badge-primary"> &#x20b9 {{prod.price}} </p>

                        </div>
                    {% endfor %}

                        
                    </div>


                    
                    

                </div>
                <!-- product listing section ends  -->
               







                <!-- products categories section   -->
                <div class="col-md-3">
                    <h3 class="text text-info"> Categories</h3>
                    <hr>
                    <a href="  {% url 'shop:product_list' %} "><span class="badge badge-secondary"> ALL CATEGORIES </span></a>
                    {% for c in categories %}
                    <div class="col-sm">

                        <a href="  {{c.get_absolute_url}} "><span class="badge badge-danger"> {{c.name}} </span></a>

                    
                    
                    </div>
                    {% endfor %}
                    
                    
                </div>
                <!-- products categories section ends  -->




            </div>
        

        </div>




              
{% endblock content %}

shop/templates/shop/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href=" {% url 'shop:product_list' %} ">EcomWeb</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active pt-3">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item pt-3">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown pt-3">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item ">
                {% with total_items=cart|length %}

                {% if cart|length > 0 %}

                Your cart:
                <p class=" btn btn-outline-success mr-2 mt-3"> <a href=" {% url 'cart:cart_detail'  %}" class="text text-white" >
                        {{total_items}} item {{total_item|pluralize}},
                        ${{cart.get_total_price}}
                    </a> </p>
               

                {%  else %}

                      <p class="text text-warning nav-link">Your cart is empty</p>

                  
                {% endif %}

                

                  
                {% endwith %}
               

            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>